image: golang:latest

stages:
  - test
  - build

before_script:
    - mkdir -p /go/src/github.com/josegomezr/
    - ln -s $CI_PROJECT_DIR /go/src/github.com/josegomezr/gotp
    - cd /go/src/github.com/josegomezr/gotp
    - make dep

tests:
  stage: test
  script:
    - make test
    - make race
    - make lint
    - make coverage

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  artifacts:
    paths:
      - coverage
  only:
  - master

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
    - code
